name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe your idea below.

  - type: textarea
    id: problem
    attributes:
      label: Problem / Use Case
      description: Describe the problem you're trying to solve or the use case for this feature.
      placeholder: I want to be able to... / It would be helpful if...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: If you have an idea for how this could be implemented, describe it here.
      placeholder: Describe your proposed solution...
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: Describe any alternatives you've considered...
    validations:
      required: false

  - type: dropdown
    id: scope
    attributes:
      label: Feature Scope
      description: What area of the application does this feature relate to?
      options:
        - Auctions
        - Items & Bidding
        - User Management
        - Notifications
        - UI/UX
        - API
        - Self-hosting / Deployment
        - Documentation
        - Other
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to help implement this feature?
      options:
        - label: I would be willing to submit a PR for this feature
          required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or screenshots about the feature request here.
    validations:
      required: false
